# Site settings
title: KangarooBox
email: webmaster@kangaroobox.com
description: We make IT simple!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kangaroobox.com" # the base hostname & protocol for your site
twitter_username: kangaroobox
github_username:  kangaroobox
pagination: 5
permalink: /:year/:month/:day/:title

# Build settings
markdown: kramdown

# Customization
gems:
  - jekyll-gist